// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoMac.Foundation;
using MonoMac.AppKit;

namespace Zippy
{
	public partial class CustomOutlineView : NSOutlineView
	{
		public CustomOutlineView (IntPtr handle) : base (handle)
		{
		}

		public override void AwakeFromNib()
		{
			base.AwakeFromNib();
			SetDraggingSourceOperationMask(NSDragOperation.Copy, false);
		}

		public override string[] NamesOfPromisedFilesDroppedAtDestination(NSUrl dropDestination)
		{
			return null;
		}
	}
}
