// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoMac.Foundation;
using MonoMac.AppKit;

namespace Zippy
{
	public partial class CustomSplitView : NSSplitView
	{
		public CustomSplitView (IntPtr handle) : base (handle)
		{

		}

		public override float DividerThickness {
			get {
				return -1;
			}
		}
	}
}
