// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Linq;
using System.Collections.Generic;

using MonoMac.Foundation;
using MonoMac.AppKit;

namespace Zippy
{
	public partial class CustomTableView : NSTableView
	{
		public DecompressionHandler decomp;

		public CustomTableView (IntPtr handle) : base (handle)
		{
		}

		public override void AwakeFromNib()
		{
			base.AwakeFromNib();
			SetDraggingSourceOperationMask(NSDragOperation.Copy, false);
		}

		public void MakeColumns(List<string> headers)
		{
			foreach (NSTableColumn c in TableColumns())
			{
				RemoveColumn(c);
			}

			headers.ForEach((header) => {
				NSTableColumn col = new NSTableColumn();
				col.HeaderCell.Title = header; 
				col.Identifier = header;

				AddColumn(col);
			});
		}

		public override string[] NamesOfPromisedFilesDroppedAtDestination(NSUrl dropDestination)
		{
			return decomp(dropDestination);
		}
	}
}
